;(function () {

  /**
   * 判斷欄位是否應排除在 INSERT 之外。
   * AUTO_INCREMENT / SERIAL 欄位由資料庫自動填入，不需手動指定。
   * @param {Object} col - ColumnDef
   */
  function isAutoGenerated(col) {
    return col.isAutoIncrement
  }

  /**
   * 依欄位型別產生對應的佔位符。
   * 業務背景：不同佔位符風格對應不同 SQL 驅動程式慣例：
   *   named（:col_name）常見於 Python SQLAlchemy、PHP PDO；
   *   positional（?）常見於 JDBC、原生 MySQL/MariaDB。
   * @param {Object} col - ColumnDef
   * @param {'named'|'positional'} style
   */
  function placeholder(col, style) {
    if (style === 'positional') return '?'
    return `:${col.name}`
  }

  /**
   * 產生 INSERT 模板。
   * 排除 AUTO_INCREMENT 欄位（由 DB 自動產生，無需傳值）；
   * NOT NULL 欄位加 /* required */ 註解提示呼叫端必填。
   * @param {Object} table - TableSchema
   * @param {'named'|'positional'} style
   * @returns {string}
   */
  function buildInsert(table, style = 'named') {
    const cols = table.columns.filter(c => !isAutoGenerated(c))
    if (cols.length === 0) return `-- ${table.tableName} 所有欄位皆為自動產生`

    const colNames = cols.map(c => c.name).join(',\n  ')
    const values = cols.map(c => {
      const ph = placeholder(c, style)
      return c.nullable === false ? `${ph} /* required */` : ph
    }).join(',\n  ')

    return `INSERT INTO ${table.tableName} (\n  ${colNames}\n) VALUES (\n  ${values}\n);`
  }

  /**
   * 產生 UPDATE 模板。
   * WHERE 條件固定為 PK 欄位，其餘欄位作為可更新欄位。
   * 業務背景：UPDATE 必須帶 PK 條件，避免一句 SQL 意外更新全表造成資料損毀。
   * @param {Object} table - TableSchema
   * @param {'named'|'positional'} style
   * @returns {string}
   */
  function buildUpdate(table, style = 'named') {
    const pkCols = table.columns.filter(c => table.primaryKeys.includes(c.name))
    const updateCols = table.columns.filter(c => !table.primaryKeys.includes(c.name) && !isAutoGenerated(c))

    if (pkCols.length === 0) {
      return `-- ${table.tableName} 未定義 PRIMARY KEY，無法產生安全的 UPDATE 模板`
    }
    if (updateCols.length === 0) {
      return `-- ${table.tableName} 無可更新的欄位（所有欄位皆為 PK 或自動產生）`
    }

    const setClauses = updateCols.map(c => `  ${c.name} = ${placeholder(c, style)}`).join(',\n')
    const whereClauses = pkCols.map(c => `${c.name} = ${placeholder(c, style)}`).join(' AND ')

    return `UPDATE ${table.tableName}\nSET\n${setClauses}\nWHERE ${whereClauses};`
  }

  /**
   * 產生 DELETE 模板。
   * 僅以 PK 為 WHERE 條件，並附加操作安全提示。
   * 業務背景：DELETE 是不可逆操作，必須強制帶 PK 條件防止誤刪全表；
   *   無 PK 的資料表直接拒絕產生，需人工確認安全條件再執行。
   * @param {Object} table - TableSchema
   * @param {'named'|'positional'} style
   * @returns {string}
   */
  function buildDelete(table, style = 'named') {
    const pkCols = table.columns.filter(c => table.primaryKeys.includes(c.name))

    if (pkCols.length === 0) {
      return `-- ⚠ ${table.tableName} 未定義 PRIMARY KEY，拒絕產生 DELETE 模板（避免全表刪除風險）`
    }

    const whereClauses = pkCols.map(c => `${c.name} = ${placeholder(c, style)}`).join(' AND ')

    return `-- ⚠ 執行前請確認 WHERE 條件正確，此操作不可逆\nDELETE FROM ${table.tableName}\nWHERE ${whereClauses};`
  }

  window.dmlBuilder = { buildInsert, buildUpdate, buildDelete }
})()
